# Generated by Django 4.2.7 on 2024-04-13 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('SELLER', 'Seller'), ('WORKSHOP', 'Workshop'), ('DRIVER', 'Driver'), ('ADMIN', 'ADMIN'), ('BLOCK', 'Block')], default='ADMIN', max_length=50, null=True, verbose_name='Type'),
        ),
    ]
