# Generated by Django 4.2.7 on 2023-12-18 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
