# Generated by Django 4.2.7 on 2023-12-08 18:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0003_delete_hotel_delivery_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
