# Generated by Django 4.2.7 on 2023-12-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0004_alter_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
