# Generated by Django 4.2.7 on 2023-12-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0005_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='location',
        ),
    ]
