# Generated by Django 4.2.7 on 2023-12-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0009_remove_delivery_user_delivery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_bollen',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='add_delvery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.delivery')),
            ],
        ),
    ]
