# Generated by Django 4.2.7 on 2023-12-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0010_delivery_order_bollen_add_delvery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('rejected', 'rejected'), ('completed', 'completed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
