# Generated by Django 4.2.7 on 2024-03-17 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.sections'),
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.carmodel'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.products'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='orders',
            field=models.ManyToManyField(related_name='deliveries', to='cardb.order'),
        ),
        migrations.AddField(
            model_name='companycar',
            name='countrycar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.countrycar'),
        ),
        migrations.AddField(
            model_name='carname',
            name='companycar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.companycar'),
        ),
        migrations.AddField(
            model_name='carname',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carname',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.carmodel'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.companycar'),
        ),
        migrations.AddField(
            model_name='add_delvery',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.delivery'),
        ),
    ]
