# Generated by Django 4.2.7 on 2024-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0002_remove_delivery_status_add_delvery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
