# Generated by Django 4.2.7 on 2024-03-19 22:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='products_gallery/'),
        ),
    ]
