# Generated by Django 4.2.7 on 2023-12-08 17:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0002_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
