# Generated by Django 4.2.7 on 2023-12-09 11:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0006_remove_delivery_address_remove_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
