# Generated by Django 4.2.7 on 2023-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0011_delivery_status_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
